### ISSUE TITLE
Fails to compile in clean chroot

### ISSUE THREAD

**Issue by laceflower** [netblock/yaabe#1]
Hi, I find this program pretty useful and I'm trying to package it for Arch Linux's AUR (if you'd like that).

It builds successfully in my regular environment but the object gtk_yaabe_gtk4.c.o fails when built in a clean chroot. This is presumably due to the following warnings being treated as errors from the `-Werror=format-security` and -`Wformat` flags, but I may be wrong.
I'm building with gcc using ninja as meson's backend, having set up the build with --buildtype=release and -Db_lto.

```
FAILED: libyaabe.a.p/gtk_yaabe_gtk4.c.o
../gtk/yaabe_gtk4.c: In function ‘generic_error_popup’:
../gtk/yaabe_gtk4.c:872:9: error: format not a string literal and no format arguments [-Werror=format-security]
  872 |         GtkAlertDialog* const alert = gtk_alert_dialog_new(primary);
      |         ^~~~~~~~~~~~~~
     
../gtk/yaabe_gtk4.c: In function ‘filer_error_window’:
../gtk/yaabe_gtk4.c:1759:9: error: format not a string literal and no format arguments [-Werror=format-security]
 1759 |         GtkAlertDialog* const alert = gtk_alert_dialog_new(title);
      |         ^~~~~~~~~~~~~~

cc1: some warnings being treated as errors
```

I appreciate any help or fixes you might be able to provide.

**Comment by netblock** [comment]
Please try again with the above change
                                                                                
I would like it packaged for Arch's AUR, thank you!

**Comment by laceflower** [comment]
It builds cleanly now. Thank you for your help, the package is now live [here](https://aur.archlinux.org/packages/yaabe-git)
