### ISSUE TITLE
AMD RADEON 530 VBIOS CLOSES IMMEDIATELY AFTER OPENING

### ISSUE THREAD

**Issue by chris1892006** [netblock/yaabe#2]
AMD RADEON 530 VBIOS CLOSES IMMEDIATELY AFTER OPENING
VBIOS
[AMD_RADEON_530_VBIOS_ORIGINAL_UNTOUCHED.zip](https://github.com/user-attachments/files/17100586/AMD_RADEON_530_VBIOS_ORIGINAL_UNTOUCHED.zip)

v0.4.0 and below opens it but most everything is missing.  Can you make it open it and shows the PowerPlay table & Powertune & NonClockInfo?

**Comment by chris1892006** [comment]
Can you help me @netblock?  Please & Thank you for your wonderful software.
https://www.mediafire.com/file/p2nazbdb6n50wha/AMD_RADEON_530_VBIOS.bin/file

**Comment by netblock** [comment]
Please try again with the above change
