### ISSUE TITLE
Error Building : build stopped: subcommand failed

### ISSUE THREAD

**Issue by chris1892006** [netblock/yaabe#4]
build stopped: subcommand failed
![image](https://github.com/user-attachments/assets/cc5c4de9-8f62-4a19-a3e2-609f0842ba76)
![image (1)](https://github.com/user-attachments/assets/e763948c-eab9-4ec4-8956-06a393cd6e54)

**Comment by netblock** [comment]
This is probably a MSVCRT problem, where it's just outdated. Moving the recommended [MSYS2 environment from MINGW64 to UCRT64](https://www.msys2.org/docs/environments/) so YAABE can have the UCRT library might probably fix this.

UCRT may break YAABE installations on older windows such as WinXP, but [there are multiple ways to deploy UCRT](https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment).

**Comment by chris1892006** [comment]
> This is probably a MSVCRT problem, where it's just outdated. Moving the recommended [MSYS2 environment from MINGW64 to UCRT64](https://www.msys2.org/docs/environments/) so YAABE can have the UCRT library might probably fix this.
> 
> UCRT may break YAABE installations on older windows such as WinXP, but [there are multiple ways to deploy UCRT](https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment).

Will update you later soon once we try again.  Thx

**Comment by netblock** [comment]
It was a C23 compatibility issue that UCRT couldn't fix. 

Please try again with the above change.

**Comment by chris1892006** [comment]
We successfully compiled it but it's dark for some reason & the close minimize and maximize buttons are missing?  
![yaabe_Up5umlLtxT](https://github.com/user-attachments/assets/9643ca4c-b36e-4051-8110-941aa236b5a1)
